import type { Metadata } from "next";
import "./globals.css";
import "react-responsive-carousel/lib/styles/carousel.min.css";
import { ParallaxProvider } from "@/components/parallax";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="text-white">
      <body>
        <ParallaxProvider>
          {children}
        </ParallaxProvider>
      </body>
    </html>
  );
}
